# Generated by Django 5.0.6 on 2024-06-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_period',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=10),
        ),
    ]
