# Generated by Django 5.0.6 on 2024-06-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_subscription_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(choices=[('PimpMyEnglishMonthly', 'PimpMyEnglishMonthly'), ('PimpMyEnglishYearly', 'PimpMyEnglishYearly')], default='PimpMyEnglishMonthly', max_length=50),
        ),
    ]
