# Generated by Django 5.0.6 on 2024-06-13 00:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField(default=10)),
                ('cefr_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), default=list, size=None)),
                ('word_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=None)),
            ],
        ),
    ]
