# Generated by Django 5.0.6 on 2024-06-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsets', '0003_wordset_words_delete_wordinset'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='start_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wordset',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
