# Generated by Django 5.0.6 on 2024-07-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsets', '0004_wordset_start_count_alter_wordset_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
